name: CI

on:
  push:
    branches: [main, versions]

  pull_request:
    branches: [main]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: swift test -v

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: swift test -v
